const ADD_TEST_SUITE = 'ADD_TEST_SUITE'
const REMOVE_TEST_SUITE = 'REMOVE_TEST_SUITE'
const REMOVE_TEST_SITE_WITH_RELATED_CASES = 'REMOVE_TEST_SITE_WITH_RELATED_CASES'
const UPDATE_TEST_SUITE = 'UPDATE_TEST_SUITE'

const ADD_TEST_CASE = 'ADD_TEST_CASE'
const REMOVE_TEST_CASE = 'REMOVE_TEST_CASE'
const UPDATE_TEST_CASE = 'UPDATE_TEST_CASE'

export {
  ADD_TEST_SUITE,
  REMOVE_TEST_SUITE,
  UPDATE_TEST_SUITE,
  REMOVE_TEST_SITE_WITH_RELATED_CASES,
  ADD_TEST_CASE,
  REMOVE_TEST_CASE,
  UPDATE_TEST_CASE
}
